### ISSUE TITLE
Link for project's deployed version on heroku.

### ISSUE THREAD

**Issue by manupatel007** [ahmishra/Flask-ChatApp#1]
Please put the link of deployed app.

**Comment by ahmishra** [comment]
There are currently some problems with the online version of the current version of the Chat App. I wouldn't reccomend using it right now, instead try using the local version, the link for the online version is- https://openbrainstorm.herokuapp.com/

**Comment by ahmishra** [comment]
@manupatel007 

I'm going to bring down the online web version of the app so From 9:15 AM IST onwards that site won't be accessible by anyone because of debugging and package structuring error, but there's a Good News, too now you can use this app to connect with your friends on a local network means the same at as you are connected to! more details on this question in the README
